// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Part1.ConsoleApp.Infrastructure.Persistence;

#nullable disable

namespace Part1.ConsoleApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250723012413_PrimeraMigracion")]
    partial class PrimeraMigracion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Part1.ConsoleApp.Domain.Entities.Distribuidor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Telefono")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Distribuidor", (string)null);
                });

            modelBuilder.Entity("Part1.ConsoleApp.Domain.Entities.Marca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DistribuidorId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DistribuidorId");

                    b.ToTable("Marca", (string)null);
                });

            modelBuilder.Entity("Part1.ConsoleApp.Domain.Entities.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DistribuidorId")
                        .HasColumnType("int");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<int>("MarcaId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Precio")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("TipoProducto")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("Id");

                    b.HasIndex("DistribuidorId");

                    b.HasIndex("MarcaId");

                    b.ToTable("Producto", (string)null);

                    b.HasDiscriminator<string>("TipoProducto").HasValue("Producto");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Part1.ConsoleApp.Domain.Entities.TipoMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TipoMaterial", (string)null);
                });

            modelBuilder.Entity("Part1.ConsoleApp.Domain.Entities.Filamento", b =>
                {
                    b.HasBaseType("Part1.ConsoleApp.Domain.Entities.Producto");

                    b.Property<float>("Peso")
                        .HasColumnType("real");

                    b.Property<int>("TipoMaterialId")
                        .HasColumnType("int");

                    b.HasIndex("TipoMaterialId");

                    b.HasDiscriminator().HasValue("Filamento");
                });

            modelBuilder.Entity("Part1.ConsoleApp.Domain.Entities.Insumo", b =>
                {
                    b.HasBaseType("Part1.ConsoleApp.Domain.Entities.Producto");

                    b.HasDiscriminator().HasValue("Insumo");
                });

            modelBuilder.Entity("Part1.ConsoleApp.Domain.Entities.Marca", b =>
                {
                    b.HasOne("Part1.ConsoleApp.Domain.Entities.Distribuidor", "Distribuidor")
                        .WithMany("Marcas")
                        .HasForeignKey("DistribuidorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Distribuidor");
                });

            modelBuilder.Entity("Part1.ConsoleApp.Domain.Entities.Producto", b =>
                {
                    b.HasOne("Part1.ConsoleApp.Domain.Entities.Distribuidor", "Distribuidor")
                        .WithMany("Productos")
                        .HasForeignKey("DistribuidorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Part1.ConsoleApp.Domain.Entities.Marca", "Marca")
                        .WithMany("Productos")
                        .HasForeignKey("MarcaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Distribuidor");

                    b.Navigation("Marca");
                });

            modelBuilder.Entity("Part1.ConsoleApp.Domain.Entities.Filamento", b =>
                {
                    b.HasOne("Part1.ConsoleApp.Domain.Entities.TipoMaterial", "TipoMaterial")
                        .WithMany()
                        .HasForeignKey("TipoMaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoMaterial");
                });

            modelBuilder.Entity("Part1.ConsoleApp.Domain.Entities.Distribuidor", b =>
                {
                    b.Navigation("Marcas");

                    b.Navigation("Productos");
                });

            modelBuilder.Entity("Part1.ConsoleApp.Domain.Entities.Marca", b =>
                {
                    b.Navigation("Productos");
                });
#pragma warning restore 612, 618
        }
    }
}
